version: "3"

services:
  microservice:
    container_name: backk-example-microservice
    restart: always
    build: .
    env_file: .env.ci
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.7
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: bitnami/kafka:2.8.1
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  redis:
    container_name: redis
    image: redis:6.2.6
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  redis-cache:
    container_name: redis-cache
    image: redis:6.2.6
    restart: always
    ports:
      - "${REDIS_CACHE_PORT}:6379"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
