# https://cloudnweb.dev/2019/09/building-a-production-ready-node-js-app-with-typescript-and-docker/

version: "3"

services:
  microservice:
    container_name: backk-example-microservice
    restart: always
    build: .
    env_file: .env.ci
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
