openapi: 3.0.3
info:
  title: backk-example-microservice API
  description: ""
  version: 1.0.72
servers:
  - url: http://localhost:3000/backk-example-microservice.default
    description: Local development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
security:
  - bearerAuth: []
paths: {}
