#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

# Remove all below if you want to disable automatic client generation
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $BRANCH == main ]] || [[ $BRANCH == master ]]; then
  echo 'Generating clients...This might take a while.'
  echo 'If you want to disable automatic client generation, remove client generation section in .husky/pre-commit'
  npm run generateClientsOnly > /dev/null
  git add generated/clients > /dev/null
fi
