name: Continuous integration workflow
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Static code analysis with SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: "Legal and compliance with FOSSA test"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: false

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Get latest git tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: getLatestTag

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extractBranch

      - name: Set build version
        uses: haya14busa/action-cond@v1
        id: buildVersion
        with:
          cond: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*' }}
          if_true: "${{ steps.getLatestTag.outputs.tag }}"
          if_false: "${{ steps.extract_branch.outputs.branch }}-${{ github.run_attempt }}-${{ github.sha }}"

      - name: Build and push Docker image when in feature branch
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/v*'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/backk-example-microservice:${{ steps.buildVersion.outputs.value }}

      - name: Extract metadata for building and publish Docker image when in main or maintenance branch
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*'
        id: dockerImageMetadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/backk-example-microservice
          tags: |
            type=semver,pattern={{version}},value=${{ steps.buildVersion.outputs.value }}

      - name: Build and push Docker image when in main or maintenance branch
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*'
        id: dockerImageBuildAndPush
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.dockerImageMetadata.outputs.tags }}
          labels: ${{ steps.dockerImageMetadata.outputs.labels }}

      - name: Docker image vulnerability scan
        id: anchoreScan
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/backk-example-microservice:latest
          fail-build: false
          severity-cutoff: high

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.anchoreScan.outputs.sarif }}

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Set microservice version from tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*'
        id: microserviceVersionFromTag
        run: |
          value=$(echo ${${{ steps.buildVersion.outputs.value }}:1})
          echo "::set-output name=value::$value"

      - name: Set microservice version
        uses: haya14busa/action-cond@v1
        id: microserviceVersion
        with:
          cond: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*' }}
          if_true: "${{ steps.microserviceVersionFromTag.output.value }}"
          if_false: "${{ steps.buildVersion.output.value }}"

      - name: Update helm chart versions
        run: |
          sed -i "/^version: .*/version: ${{ steps.microserviceVersion.outputs.value }}/g" helm/backk-example-microservice/Chart.yaml
          sed -i "/^appVersion: .*/appVersion: '${{ steps.microserviceVersion.outputs.value }}'/g" helm/backk-example-microservice/Chart.yaml

      - name: Define docker image tag
        uses: haya14busa/action-cond@v1
        id: dockerImageTag
        with:
          cond: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v*' }}
          if_true: "${{ steps.microserviceVersion.outputs.value }}@${{ steps.dockerImageBuildAndPush.outputs.digest }"
          if_false: "${{ steps.microserviceVersion.outputs.value }}"

      - name: Update Docker image tag in values.yaml
        run: |
          sed -i "/^imageTag:.*/imageTag: ${{ steps.dockerImageTag.outputs.value }}/g" helm/backk-example-microservice/values.yaml

      - name: Lint Helm chart
        run: helm lint helm/backk-example-microservice

      - name: Package and publish Helm chart
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
